//! Local hostnames and the reverse-proxy config generated from them.
//!
//! One file is the source of truth and the Caddyfile is an artefact rebuilt
//! from it every time. The tool this replaces kept the hostnames in one file
//! and the ports they pointed at in another, so the two could disagree and
//! neither was wrong on its own.

use serde::{Deserialize, Serialize};

#[derive(Debug, thiserror::Error)]
pub enum DomainError {
    #[error("domains file is not valid TOML: {0}")]
    Parse(#[from] toml::de::Error),
    #[error("{0} is already routed; remove it first or choose another host")]
    DuplicateHost(String),
    #[error("upstream {0:?} must be written as container:port")]
    InvalidUpstream(String),
    #[error("host {0:?} is not a usable hostname")]
    InvalidHost(String),
    #[error("{0} is not routed")]
    NotFound(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
pub struct Domain {
    pub host: String,
    pub upstream: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize, Serialize)]
pub struct DomainSet {
    #[serde(default, rename = "domain")]
    domains: Vec<Domain>,
}

impl DomainSet {
    pub fn from_toml_str(text: &str) -> Result<Self, DomainError> {
        let raw: DomainSet = toml::from_str(text)?;

        // Held to exactly the rule `add` holds a hostname to. Reading the file
        // used to skip this, so the same name was legal or illegal depending
        // on which way it arrived - and what came off disk went straight into
        // the generated config, where a newline and a brace close one block
        // and open another. Normalising here also means a name typed into the
        // file by hand comes back the way the command would have written it.
        let mut set = DomainSet::default();
        for domain in raw.domains {
            let host = normalise_host(&domain.host)?;
            let upstream = validated_upstream(&domain.upstream)?;
            // A file listing one host twice makes the generated config
            // ambiguous, and picking either block silently would be a guess.
            if set.domains.iter().any(|seen| seen.host == host) {
                return Err(DomainError::DuplicateHost(host));
            }
            set.domains.push(Domain { host, upstream });
        }

        set.domains.sort_by(|a, b| a.host.cmp(&b.host));
        Ok(set)
    }

    pub fn add(&mut self, host: &str, upstream: &str) -> Result<(), DomainError> {
        let host = normalise_host(host)?;
        let upstream = validated_upstream(upstream)?;
        if self.domains.iter().any(|domain| domain.host == host) {
            return Err(DomainError::DuplicateHost(host));
        }
        self.domains.push(Domain { host, upstream });
        // A set of routes has no meaningful insertion order. Keeping it sorted
        // means what is stored, what is emitted, and what is read back are the
        // same thing.
        self.domains.sort_by(|a, b| a.host.cmp(&b.host));
        Ok(())
    }

    pub fn remove(&mut self, host: &str) -> Result<(), DomainError> {
        let host = normalise_host(host)?;
        let before = self.domains.len();
        self.domains.retain(|domain| domain.host != host);
        if self.domains.len() == before {
            // Reporting success for a host that was never there would let a
            // typo look like a completed removal.
            return Err(DomainError::NotFound(host));
        }
        Ok(())
    }

    pub fn hosts(&self) -> Vec<String> {
        self.sorted()
            .into_iter()
            .map(|domain| domain.host.clone())
            .collect()
    }

    pub fn entries(&self) -> Vec<&Domain> {
        self.sorted()
    }

    pub fn is_empty(&self) -> bool {
        self.domains.is_empty()
    }

    /// Sorted by host so that regenerating without changing anything produces
    /// a byte-identical file instead of a spurious diff.
    fn sorted(&self) -> Vec<&Domain> {
        let mut sorted: Vec<&Domain> = self.domains.iter().collect();
        sorted.sort_by(|a, b| a.host.cmp(&b.host));
        sorted
    }

    /// Written by hand rather than through a serializer: every host and
    /// upstream is validated on the way in, so the output cannot need escaping
    /// and this cannot fail.
    pub fn to_toml_string(&self) -> String {
        let mut out =
            String::from("# Managed by adev. Change it with `adev domains add` or `remove`.\n");
        for domain in self.sorted() {
            out.push_str(&format!(
                "\n[[domain]]\nhost = \"{}\"\nupstream = \"{}\"\n",
                domain.host, domain.upstream
            ));
        }
        out
    }

    pub fn to_caddyfile(&self) -> String {
        let mut out = String::from(
            "# Generated by adev from the domains file. Do not edit by hand:\n\
             # every change here is overwritten the next time a domain changes.\n",
        );
        for domain in self.sorted() {
            out.push_str(&format!(
                "\nhttp://{} {{\n    reverse_proxy {}\n}}\n",
                domain.host, domain.upstream
            ));
        }
        out
    }
}

/// Accepts what a person would actually type - a pasted URL, a stray trailing
/// slash, a capital letter - and reduces it to the one spelling stored, so the
/// same domain cannot be added twice wearing a different coat.
fn normalise_host(host: &str) -> Result<String, DomainError> {
    // Lowercased first, then stripped: the other way round, a scheme typed as
    // HTTP:// survives the strip and is then refused for containing a colon.
    // Hostnames are case-insensitive and so are the schemes in front of them.
    let cleaned = host
        .trim()
        .to_lowercase()
        .trim_start_matches("https://")
        .trim_start_matches("http://")
        .trim_end_matches('/')
        .to_string();

    let usable = !cleaned.is_empty()
        && cleaned
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-');
    if !usable {
        return Err(DomainError::InvalidHost(host.to_string()));
    }
    Ok(cleaned)
}

/// An upstream names a container and the port it listens on inside the docker
/// network, which is not the port published to the host.
fn validated_upstream(upstream: &str) -> Result<String, DomainError> {
    let refused = || DomainError::InvalidUpstream(upstream.to_string());
    let (container, port) = upstream.trim().rsplit_once(':').ok_or_else(refused)?;

    let container_ok = !container.is_empty()
        && container
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == '_');
    let port_ok = port.parse::<u16>().is_ok_and(|port| port > 0);
    if !container_ok || !port_ok {
        return Err(refused());
    }
    Ok(format!("{container}:{port}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn a_set() -> DomainSet {
        let mut set = DomainSet::default();
        set.add("kafka.localhost", "kafka-ui:8080").unwrap();
        set.add("db.localhost", "dbgate-ui:3000").unwrap();
        set
    }

    #[test]
    fn a_host_is_normalised_so_the_same_domain_cannot_arrive_twice_in_disguise() {
        let mut set = DomainSet::default();
        set.add("http://Db.localhost/", "dbgate-ui:3000").unwrap();
        assert_eq!(set.hosts(), vec!["db.localhost"]);

        let err = set.add("db.localhost", "other:80").unwrap_err();
        assert!(matches!(err, DomainError::DuplicateHost(_)), "got {err:?}");
    }

    #[test]
    fn an_upstream_must_name_both_a_container_and_a_port() {
        let mut set = DomainSet::default();
        for bad in [
            "dbgate-ui",
            "dbgate-ui:",
            ":3000",
            "dbgate-ui:http",
            "dbgate-ui:0",
        ] {
            let err = set.add("x.localhost", bad).unwrap_err();
            assert!(
                matches!(err, DomainError::InvalidUpstream(_)),
                "{bad} should be refused, got {err:?}"
            );
        }
        assert!(set.add("x.localhost", "dbgate-ui:3000").is_ok());
    }

    #[test]
    fn an_empty_host_is_refused_rather_than_written_as_a_broken_block() {
        let mut set = DomainSet::default();
        let err = set.add("   ", "dbgate-ui:3000").unwrap_err();
        assert!(matches!(err, DomainError::InvalidHost(_)), "got {err:?}");
    }

    #[test]
    fn removing_a_host_that_was_never_there_says_so_instead_of_succeeding_quietly() {
        let mut set = a_set();
        assert!(set.remove("db.localhost").is_ok());
        let err = set.remove("db.localhost").unwrap_err();
        assert!(matches!(err, DomainError::NotFound(_)), "got {err:?}");
        assert_eq!(set.hosts(), vec!["kafka.localhost"]);
    }

    #[test]
    fn the_caddyfile_is_generated_in_a_stable_order() {
        let forward = a_set();
        let mut backward = DomainSet::default();
        backward.add("db.localhost", "dbgate-ui:3000").unwrap();
        backward.add("kafka.localhost", "kafka-ui:8080").unwrap();
        assert_eq!(
            forward.to_caddyfile(),
            backward.to_caddyfile(),
            "the same domains added in a different order must produce the same file, \
             or every regeneration shows up as a spurious change"
        );
    }

    #[test]
    fn the_caddyfile_warns_that_it_is_generated() {
        let caddyfile = a_set().to_caddyfile();
        assert!(
            caddyfile
                .lines()
                .next()
                .unwrap_or_default()
                .starts_with('#'),
            "a file that is overwritten without asking must say so on line one"
        );
        assert!(caddyfile.to_lowercase().contains("generated"));
    }

    #[test]
    fn the_caddyfile_contains_exactly_the_domains_configured() {
        let caddyfile = a_set().to_caddyfile();
        assert!(caddyfile.contains("http://db.localhost {"));
        assert!(caddyfile.contains("reverse_proxy dbgate-ui:3000"));
        assert!(caddyfile.contains("http://kafka.localhost {"));
        assert!(caddyfile.contains("reverse_proxy kafka-ui:8080"));
        assert_eq!(
            caddyfile.matches("reverse_proxy").count(),
            2,
            "one upstream per domain, no more and no fewer"
        );
    }

    #[test]
    fn an_empty_set_still_produces_a_valid_file_rather_than_nothing() {
        let caddyfile = DomainSet::default().to_caddyfile();
        assert!(caddyfile.starts_with('#'));
        assert!(!caddyfile.contains("reverse_proxy"));
    }

    #[test]
    fn a_domain_set_survives_a_round_trip_through_toml() {
        let original = a_set();
        let text = original.to_toml_string();
        let parsed = DomainSet::from_toml_str(&text).unwrap();
        assert_eq!(parsed, original);
    }

    #[test]
    fn an_absent_domains_file_reads_as_an_empty_set_not_an_error() {
        assert_eq!(DomainSet::from_toml_str("").unwrap(), DomainSet::default());
    }

    #[test]
    fn malformed_toml_is_reported_rather_than_silently_dropping_every_domain() {
        let err = DomainSet::from_toml_str("[[domain]\nhost =").unwrap_err();
        assert!(matches!(err, DomainError::Parse(_)), "got {err:?}");
    }

    #[test]
    fn a_stored_file_that_repeats_a_host_is_refused_on_load() {
        let text = "[[domain]]\nhost = \"a.localhost\"\nupstream = \"x:1\"\n\
                    [[domain]]\nhost = \"a.localhost\"\nupstream = \"y:2\"\n";
        let err = DomainSet::from_toml_str(text).unwrap_err();
        assert!(
            matches!(err, DomainError::DuplicateHost(_)),
            "two blocks for one host makes the generated file ambiguous, got {err:?}"
        );
    }

    #[test]
    fn a_host_in_the_file_is_held_to_the_same_rule_as_one_that_was_added() {
        // `add` refuses these. Reading the file used not to, so the same
        // hostname was legal or illegal depending on which way it arrived -
        // and what came off disk went straight into the generated config.
        for hostile in [
            "shop.test {\n    respond \"anything\"\n}\nhttp://other.test",
            "has a space.test",
            "semi;colon.test",
        ] {
            let written = format!("[[domain]]\nhost = {hostile:?}\nupstream = \"web:80\"\n");
            assert!(
                DomainSet::from_toml_str(&written).is_err(),
                "{hostile:?} would have been written into the Caddyfile as it stands"
            );
        }
    }

    #[test]
    fn an_upstream_in_the_file_is_held_to_the_same_rule_too() {
        let written = "[[domain]]\nhost = \"shop.test\"\nupstream = \"web:notaport\"\n".to_string();
        assert!(DomainSet::from_toml_str(&written).is_err());
    }

    #[test]
    fn a_file_written_by_hand_comes_back_in_the_shape_the_command_would_have_made() {
        // Somebody typing into the file rather than using the command should
        // not get a different result from the same hostname.
        let set = DomainSet::from_toml_str(
            "[[domain]]\nhost = \"HTTP://Shop.Test/\"\nupstream = \"web:80\"\n",
        )
        .expect("a hostname the command would have accepted");

        assert_eq!(
            set.entries()[0].host,
            "shop.test",
            "lowercased and stripped, the same way `adev domains add` does it"
        );
    }

    #[test]
    fn nothing_in_a_generated_caddyfile_can_close_the_block_it_is_inside() {
        let mut set = DomainSet::default();
        set.add("shop.test", "web:80").unwrap();
        let written = set.to_caddyfile();

        // Two braces per route and no more: one opening, one closing.
        assert_eq!(
            written.matches('{').count(),
            written.matches('}').count(),
            "a config whose braces do not balance is a config caddy will not load"
        );
        assert!(written.contains("http://shop.test {"));
        assert!(written.contains("reverse_proxy web:80"));
    }
}
